# Generated by Django 4.2.1 on 2024-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_json', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botphrases',
            name='phrases',
            field=models.TextField(),
        ),
    ]
