# Generated by Django 4.2.1 on 2024-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_json', '0002_alter_botphrases_phrases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botphrases',
            name='phrases',
            field=models.JSONField(),
        ),
    ]
