# Generated by Django 4.2.1 on 2024-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_json', '0005_alter_botphrases_phrases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botphrases',
            name='phrases',
            field=models.FileField(upload_to='', verbose_name='Файл с фразами в формате .json'),
        ),
    ]
