# Generated by Django 4.2.1 on 2024-04-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_json', '0006_alter_botphrases_phrases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botphrases',
            options={'verbose_name': 'Файл фраз бота', 'verbose_name_plural': 'Файлы фраз бота'},
        ),
        migrations.AlterField(
            model_name='botphrases',
            name='phrases',
            field=models.FileField(upload_to='phrases/', verbose_name='Файл с фразами в формате .json'),
        ),
    ]
