version: '3'

# подключаем тома-хранилаща
volumes:
  pgdata:
  nginx_logs:

services:

  nginx:
    restart: always
    image: nginx:latest
    expose: 
      - 80
    ports: 
      - "80:80" 
    volumes:
      - ./django/service_project/static:/app/service_project/static
      - ./django/service_project/media:/app/service_project/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - django
  
  django:
    build:
      context: ./django/service_project # как WORKDIR
      dockerfile: Dockerfile
    volumes:
      - ./django/service_project:/app
    expose:
      - 8000
    ports: 
      - 8000:8000 
    command: gunicorn --config gunicorn.py config.wsgi:application
    depends_on:
      - postgres

  postgres: 
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
    - ./django/service_project/.env
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  tg_bot:
    build: ./tg_bot
    command: python main.py
    volumes:
      - ./tg_bot:/bot
    depends_on:
      - django
  
