version: '3'

# подключаем тома-хранилаща
volumes:
  pgdata:
  nginx_logs:

services:
  nginx:
    restart: always # при падении nginx будет стараться подняться
    image: nginx:latest # свежий nginx
    expose: 
      - 8080 # слушает внутренний 8000 порт
    ports: 
      - "80:8080" # сопоставляет внешний 80 порт с внутренним портом контейнера - 8080
    volumes:
      - ./django/service_project/static:/app/service_project/static
      - ./django/service_project/media:/app/service_project/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - django
  
  django:
    restart: always
    build: 
      context: .
      dockerfile: docker/python/Dockerfile
    volumes: 
        - ./doctor-site:/srv/www/doctor-site
    expose:
        - 8000
    ports: 
      - 8000:8000 
    command: "gunicorn -c gunicorn.py config.wsgi" # запускаем gunicorn
  
  postgres: 
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
    - ./django/service_project/.env
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
  
