version: '3'

# подключаем тома-хранилаща
volumes:
  pgdata:
  nginx_logs: # том для хранения логов

services:

  nginx:
    build: ./nginx # Указываем путь к папке с Dockerfile
    restart: always
    expose: 
      - 80
    ports:
      - "80:80"
    volumes:
      - ./django/service_project/static:/django_project/static
      - ./django/service_project/media:/django_project/media
      - nginx_logs:/var/log/nginx # Монтируем том для логов nginx
    depends_on:
      - django
  
  django:
    build:
      context: ./django/service_project # как WORKDIR
      dockerfile: Dockerfile
    volumes:
      - ./django/service_project:/django_project
    expose:
      - 8000
    ports: 
      - 8000:8000 
    command: gunicorn --config gunicorn.py config.wsgi:application
    depends_on:
      - postgres

  postgres: 
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
    - ./django/service_project/.env
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  tg_bot:
    build: ./tg_bot
    command: python main.py
    volumes:
      - ./tg_bot:/bot
    depends_on:
      - django
  
