version: '3'

volumes:
  pgdata:

services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./django/service_project/static:/django_project/static
      - ./django/service_project/media:/django_project/media
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    depends_on:
      - django

  django:
    build: ./django/service_project
    volumes:
      - ./django/service_project:/django_project
    ports: 
      - 8000:8000 
    command: gunicorn --config gunicorn.py config.wsgi:application
    depends_on:
      - postgres

  postgres: 
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
    - ./django/service_project/.env
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  tg_bot:
    build: ./tg_bot
    command: python main.py
    volumes:
      - ./tg_bot:/bot
    depends_on:
      - django
