# Generated by Django 4.2.1 on 2024-03-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор пользователя telegram')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('surname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Данные пользователя telegram',
                'verbose_name_plural': 'Данные пользователя telegram',
            },
        ),
        migrations.CreateModel(
            name='BotOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_link', models.CharField(max_length=300, verbose_name='Ссылка на товар в магазине')),
                ('size', models.IntegerField(verbose_name='Размер одежды')),
                ('shipping_method', models.CharField(choices=[('delivery_moscow', 'Доставка курьером по Москве'), ('delivery_russia', 'Доставка курьером по России'), ('delivery_pickup', 'Самовывоз')], max_length=50, verbose_name='Метод доставки')),
                ('payment_method', models.CharField(choices=[('card_ru', 'Карта РФ '), ('paypal', 'PayPal')], max_length=50, verbose_name='Метод оплаты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('waiting_for_payment', 'Ожидает оплаты'), ('delivery_in_progress', 'В процессе доставки'), ('finished', 'Завершен'), ('returned', 'Возврат')], max_length=60, verbose_name='Статус заказа')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.personaldata')),
            ],
            options={
                'verbose_name': 'Заказ в telegram боте',
                'verbose_name_plural': 'Заказы в telegram боте',
                'ordering': ['-creation_date'],
            },
        ),
    ]
