# Generated by Django 4.2.1 on 2024-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_botorder_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID заказа из платежной системы'),
        ),
    ]
