# Generated by Django 4.2.1 on 2024-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_botorder_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botorder',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Ожидает оплаты'), ('was_paid', 'Оплачен'), ('delivery_in_progress', 'В процессе доставки'), ('finished', 'Завершен'), ('returned', 'Возврат')], max_length=60, verbose_name='Статус заказа'),
        ),
    ]
