# Generated by Django 4.2.1 on 2024-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_botorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='botorder',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
