# Generated by Django 4.2.1 on 2024-04-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_botorder_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='botorder',
            name='is_real_order',
            field=models.BooleanField(default=False, verbose_name='Настоящий'),
        ),
    ]
