# Generated by Django 4.2.1 on 2024-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_botorder_is_real_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Почта'),
        ),
    ]
