# Generated by Django 4.2.1 on 2024-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_personaldata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botorder',
            name='shipping_method',
            field=models.CharField(choices=[('DELIVERY_MOSCOW', 'Доставка курьером по Москве'), ('DELIVERY_RUSSIA', 'Доставка курьером по России'), ('DELIVERY_PICKUP', 'Самовывоз')], max_length=50, verbose_name='Метод доставки'),
        ),
    ]
